name: Build Debian Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y debhelper-compat meson pkg-config rustc cargo clang libsass-dev libgtk-4-dev libadwaita-1-dev libpoppler-glib-dev libgstreamer1.0-dev libglib2.0-dev appstream-util desktop-file-utils

    - name: Build .deb package
      run: debuild -b -uc -us

    - name: Upload .deb package
      uses: actions/upload-artifact@v4
      with:
        name: rnote-deb
        path: ../*.deb
